version: '1.0'
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: vn.sh@outlook.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

  access-key-manager-db:
    image: postgres:latest
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin1234
        - POSTGRES_DB=access-key-db
    ports: 
        - "5433:5432"
    restart: always
    volumes: 
      - ./data/database-data-access-key-manager:/var/lib/postgresql/data/